ENVIRONMENT:
  MAX_EPISODE_STEPS: 500

SIMULATOR:
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128

  TYPE: "SoundSpacesSim"
  ACTION_SPACE_CONFIG: "v0"
  SCENE_DATASET: "replica"
  USE_RENDERED_OBSERVATIONS: False
  SCENE_OBSERVATION_DIR: "/home/nino/ss-lite/data/scene_observations"
  AUDIO:
    RIR_SAMPLING_RATE: 44100
    SOURCE_SOUND_DIR: "/home/nino/ss-lite/data/sounds/1s_all"
    METADATA_DIR: "/home/nino/ss-lite/data/metadata"
    BINAURAL_RIR_DIR: "/home/nino/ss-lite/data/binaural_rirs"
    MATERIALS_CONFIG_PATH: "/home/nino/ss-lite/data/material_config.json"

TASK:
  TYPE: AudioNav
  SUCCESS_DISTANCE: 1.0

  SENSORS: ['SPECTROGRAM_SENSOR']
  GOAL_SENSOR_UUID: spectrogram

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'NORMALIZED_DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL', 'NUM_ACTION', 'SUCCESS_WEIGHTED_BY_NUM_ACTION']
  SUCCESS:
    SUCCESS_DISTANCE: 1.0
  TOP_DOWN_MAP:
    MAP_RESOLUTION: 500
    DRAW_SOURCE_AND_TARGET: True
    DRAW_BORDER: True
    DRAW_SHORTEST_PATH: True

DATASET:
  TYPE: "AudioNav"
  SPLIT: "train_telephone"
  CONTENT_SCENES: ["*"]
  VERSION: "v1"
  SCENES_DIR: "/home/nino/ss-lite/data/scene_datasets/replica"
  DATA_PATH: "/home/nino/ss-lite/data/datasets/audionav/replica/{version}/{split}/{split}.json.gz"
