BASE_TASK_CONFIG_PATH: "/home/nino/ss-lite/configs/tasks/audiogoal_replica_ss2.yaml"
TRAINER_NAME: "AVNavTrainer"
NUM_PROCESSES: 1
SENSORS: ["DEPTH_SENSOR"]
VIDEO_OPTION: ["wandb"]
VISUALIZATION_OPTION: []
TEST_EPISODE_COUNT: 1

EVAL:
  SPLIT: "val_telephone"
